#!/command/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

cd "${APP_DIR}/bin" || exit
exec s6-setuidgid hotio python3 "${APP_DIR}/bin/nzbhydra2wrapperPy3.py" --nobrowser --datafolder "${CONFIG_DIR}"
