#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

# shellcheck disable=SC2086
exec s6-setuidgid hotio python3 "${APP_DIR}/bin/nzbhydra2wrapperPy3.py" --nobrowser --datafolder "${CONFIG_DIR}" ${ARGS}
