#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

redirect_cmd() {
    if [[ "${DEBUG}" == "yes" ]]; then
        "$@"
    else
        "$@" > /dev/null 2>&1
    fi
}

# shellcheck disable=SC2086
redirect_cmd exec s6-setuidgid hotio python "${APP_DIR}/nzbhydra2wrapper.py" --nobrowser --datafolder "${CONFIG_DIR}/app" ${ARGS}
